### ISSUE TITLE
Update explainer to reference window.isFramePending

### ISSUE THREAD

**Issue by foolip** [szager-chromium/isFramePending#1]
[Intent to Implement: window.isFramePending](https://groups.google.com/a/chromium.org/d/msg/blink-dev/brAJpwPoix8/FDmDG9VfDgAJ) references `window.isFramePending()`, but the explainer in this repo still calls the API `navigator.scheduling.isFramePending()`.

**Comment by szager-chromium** [comment]
The agreed-upon name is navigator.scheduling.isFramePending; I screwed up the intent.

**Comment by foolip** [comment]
Oh, I see :) Then this issue is about updating the README and whatever else still references `window.isFramePending()`.

**Comment by szager-chromium** [comment]
I did update the explainer:

https://github.com/szager-chromium/isFramePending/blob/master/explainer.md

I don't know of anywhere else that needs to be updated.

**Comment by foolip** [comment]
I saw it in the README of this repo, grep should find anything else :)

**Comment by szager-chromium** [comment]
Whoops! Fixed.

**Comment by foolip** [comment]
The repo description too, which isn't under source control :)

**Comment by szager-chromium** [comment]
Done!
